import os
import json
import asyncio
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.staticfiles import StaticFiles
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from github import Github
from backend.graph import run_generation_graph
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="Autonomous UI Generator")

# Setup paths
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FRONTEND_DIR = os.path.join(BASE_DIR, "frontend")
PREVIEW_DIR = os.path.join(FRONTEND_DIR, "preview")

# Ensure preview directory exists
os.makedirs(PREVIEW_DIR, exist_ok=True)

# Mount static files
app.mount("/preview", StaticFiles(directory=PREVIEW_DIR), name="preview")
app.mount("/static", StaticFiles(directory=FRONTEND_DIR), name="static")

@app.get("/")
async def root():
    index_path = os.path.join(FRONTEND_DIR, "index.html")
    if os.path.exists(index_path):
        with open(index_path, "r", encoding="utf-8") as f:
            return HTMLResponse(content=f.read())
    return HTMLResponse(content="<h1>Frontend not found</h1>")

class DeployRequest(BaseModel):
    repo_name: str

@app.post("/api/deploy")
async def deploy_to_github(req: DeployRequest):
    token = os.getenv("GITHUB_TOKEN")
    if not token or token.startswith("your_github_token"):
        return {"error": "Invalid or missing GitHub token in .env"}
    
    try:
        g = Github(token)
        user = g.get_user()
        
        # Check if repo exists
        try:
            repo = user.get_repo(req.repo_name)
            return {"error": f"Repository '{req.repo_name}' already exists."}
        except:
            pass
            
        # Create repo
        repo = user.create_repo(req.repo_name, description="Generated by AI Web Generator", auto_init=True)
        
        # Read files from PREVIEW_DIR
        for filename in ["index.html", "styles.css", "script.js"]:
            filepath = os.path.join(PREVIEW_DIR, filename)
            if os.path.exists(filepath):
                with open(filepath, "r", encoding="utf-8") as f:
                    content = f.read()
                    repo.create_file(filename, f"Add {filename}", content, branch="main")
                    
        # Enable GitHub Pages
        try:
            repo.edit(has_pages=True)
            repo.create_pages_site(source={"branch": "main", "path": "/"})
        except Exception as pages_e:
            print("Note: Could not automatically enable GitHub Pages (might require Pro for private repos, or API restrictions):", pages_e)
            
        return {
            "success": True,
            "url": f"https://{user.login}.github.io/{req.repo_name}/", 
            "repo_url": repo.html_url
        }
        
    except Exception as e:
        return {"error": str(e)}

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    try:
        while True:
            data = await websocket.receive_text()
            message = json.loads(data)
            
            if message.get("type") == "generate":
                prompt = message.get("prompt")
                current_code = message.get("currentCode", {})
                
                # We will pass the websocket to the graph so it can stream updates
                async def emit_log(agent, log_text, details=None):
                    await websocket.send_json({
                        "type": "log",
                        "agent": agent,
                        "text": log_text,
                        "details": details
                    })
                
                async def emit_code(html, css, js):
                    await websocket.send_json({
                        "type": "code_update",
                        "html": html,
                        "css": css,
                        "js": js
                    })
                    
                async def emit_preview_reload():
                    await websocket.send_json({
                        "type": "preview_reload"
                    })
                
                try:
                    await run_generation_graph(
                        prompt=prompt, 
                        current_code=current_code,
                        emit_log=emit_log, 
                        emit_code=emit_code,
                        emit_preview_reload=emit_preview_reload,
                        preview_dir=PREVIEW_DIR
                    )
                    await websocket.send_json({"type": "done"})
                except Exception as e:
                    await emit_log("System", f"Error: {str(e)}")
                    await websocket.send_json({"type": "error", "message": str(e)})
                    
    except WebSocketDisconnect:
        print("Client disconnected")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
